blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views


app_name = 'blogs'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),

    # Viewing pages.
    path('all_blogs/', views.all_blogs, name='all_blogs'),
    path('latest_posts/', views.latest_posts, name='latest_posts'),
    path('my_blogs/', views.my_blogs, name='my_blogs'),
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    path('posts/<int:post_id>/', views.post, name='post'),

    # Creation pages.
    path('new_blog/', views.new_blog, name='new_blog'),
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include

from . import views


app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    """A blog belonging to one user."""
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    # Most blogs are public, but some may be private for development
    #   or as a private journal.
    public = models.BooleanField(default=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title


class BlogPost(models.Model):
    """A single post belonging to a blog."""
    title = models.CharField(max_length=500)
    body = models.TextField()
    blog = models.ForeignKey(Blog, on_delete= models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    # A post is private by default, for drafting purposes.
    public = models.BooleanField(default=False)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title[:50]

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'public']


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'public' ]

blogs/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm


def index(request):
    """The home page for the blog."""
    return render(request, 'blogs/index.html')


def all_blogs(request):
    """Show all public blogs, and user's blogs."""

    # Get all public blogs, then user's blogs.
    public_blogs = Blog.objects.filter(public=True)
    if request.user.is_authenticated:
        user_blogs = Blog.objects.filter(owner=request.user)
    else:
        user_blogs = []

    context = {
        'public_blogs': public_blogs,
        'user_blogs': user_blogs,
    }
    return render(request, 'blogs/all_blogs.html', context=context)


def latest_posts(request):
    """Show latest posts from all public blogs."""

    # Get the latest 10 posts.
    public_posts = BlogPost.objects.filter(public=True).order_by('-date_added')[:10]

    context = {'public_posts': public_posts}
    return render(request, 'blogs/latest_posts.html', context=context)


@login_required
def my_blogs(request):
    """Show user's blogs."""
    user_blogs = Blog.objects.filter(owner=request.user)

    context = {'user_blogs': user_blogs}
    return render(request, 'blogs/my_blogs.html', context=context)


def blog(request, blog_id):
    """Main page for a single blog.
    Show public posts, and private posts for the current user.
    """

    blog = Blog.objects.get(id=blog_id)

    if request.user == blog.owner:
        posts = blog.blogpost_set.all().order_by('-date_added')
    else:
        posts = blog.blogpost_set.filter(public=True).order_by('-date_added')

    context = {
        'blog': blog,
        'posts': posts,
    }
    return render(request, 'blogs/blog.html', context=context)


def post(request, post_id):
    """Main page for a single post."""

    post = BlogPost.objects.get(id=post_id)

    if (not post.public) and (request.user != post.blog.owner):
        # This is someone else's private post; redirect to home page.
        return redirect('blogs:index')

    context = {
        'blog': post.blog,
        'post': post,
    }
    return render(request, 'blogs/post.html', context=context)


# --- Creation pages. ---

@login_required
def new_blog(request):
    """Create a new blog."""

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:my_blogs')

    # Display blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def new_post(request, blog_id):
    """Create a new post."""

    # Every post is associated with a specific blog.
    blog = Blog.objects.get(id=blog_id)

    # Make sure user owns this blog.
    if blog.owner != request.user:
        return redirect('blogs:index')

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog

            # If the blog is private, ensure the post is private.
            if not blog.public:
                new_post.public = False

            new_post.save()

            return redirect('blogs:post', post_id=new_post.id)

    # Display blank or invalid form.
    context = {'form': form, 'blog': blog}
    return render(request, 'blogs/new_post.html', context)


# --- Editing pages ---

# DEV: These pages aren't needed for the purpose of testing deployment, so no
#  rush on building these out.


# --- Deletion pages ---

# DEV: These pages aren't needed for the purpose of testing deployment, so no
#  rush on building these out.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    # Dsiplay a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/all_blogs.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>Public Blogs</h2>
  <ul class="list-group">
    {% for blog in public_blogs %}
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class=""><a class="text-decoration-none" href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></div>
          <span class="p-2">{{ blog.owner }}</span>
        </div>
      </li>
    {% empty %}
      There are no public blogs yet.
    {% endfor %}
  </ul>

  {% if user.is_authenticated %}
    <h2 class="pt-4 border-top border-2 mt-5">My blogs</h2>
    <ul class="list-group">
      {% for blog in user_blogs %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class=""><a class="text-decoration-none" href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></div>
          </div>
        </li>
      {% empty %}
        You don't have any blogs yet.
      {% endfor %}
    </ul>

    <div class="clearfix">
      <a class="btn btn-primary btn-md mt-4 float-end" role="button" href="{% url 'blogs:new_blog' %}">Create a new blog</a>
    </div>

  {% endif %}

{% endblock content %}

blogs/templates/blogs/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>BlogMaker Lite</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-static/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
  </head>
  <body>
    
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blogs:index' %}">BlogMaker Lite</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:all_blogs' %}">All Blogs</a>
        </li>
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'blogs:my_blogs' %}">My Blogs</a>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:latest_posts' %}">Latest Posts</a>
        </li>
      </ul>

      {% if user.is_authenticated %}
        <span class="navbar-text">Hello, {{ user.username }}.</span>
      {% endif %}

      <ul class="navbar-nav ml-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
          <form action="{% url 'users:logout' %}" method='post' class="d-flex align-items-center">
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-light btn-sm'>
              Log out</button>
          </form>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

<main class="container">
  <div class="bg-light p-5 rounded">

    {% block content %}{% endblock content %}

  </div>
</main>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      
  </body>
</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>{{ blog.title }} <span class="fs-4 fw-light">{{ blog.owner }}</span></h2>
  <h3 class="mt-4">Posts</h3>
  <ul class="list-group">
    {% for post in posts %}
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class=""><a class="text-decoration-none" href="{% url 'blogs:post' post.id %}">{{ post.title }}</a></div>
          <span class="p-2">{{ post.date_added|date:'M d, Y H:i' }}</span>
        </div>
      </li>
    {% empty %}
      There are no posts yet.
    {% endfor %}
  </ul>

  {% if user.is_authenticated %}
    {% if user == blog.owner %}
      <div class="clearfix">
        <a class="btn btn-primary btn-md mt-4 float-end" role="button" href="{% url 'blogs:new_post' blog.id %}">Create a new post</a>
      </div>
    {% endif %}
  {% endif %}

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
  
  <div class="p-3 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
      <h1 class="display-4 pb-2">BlogMaker Lite</h1>
      <p class="col-md-10 fs-4">BlogMaker Lite makes your world better by letting you share your thoughts with  the world. Make a blog today, and let us in on your thoughts and reflections!</p>
      {% if not user.is_authenticated %}
        <a class="btn btn-primary btn-lg mt-1" role="button" href="{% url 'users:register' %}">Register &raquo;</a>
      {% endif %}
    </div>
  </div>
  
{% endblock content %}

blogs/templates/blogs/latest_posts.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>Latest Posts</h2>
  <h4 class="ps-4 fw-light">from all public blogs</h4>
  <ul class="list-group">
    {% for post in public_posts %}
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class=""><a class="text-decoration-none" href="{% url 'blogs:post' post.id %}">{{ post.title }}</a></div>
          <span class="p-2">{{ post.blog }}</span>
        </div>
      </li>
    {% empty %}
      There are no public posts yet.
    {% endfor %}
  </ul>

{% endblock content %}

blogs/templates/blogs/my_blogs.html
{% extends "blogs/base.html" %}

{% block content %}

  {% if user.is_authenticated %}
    <h2>My blogs</h2>
    <ul class="list-group">
      {% for blog in user_blogs %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class=""><a class="text-decoration-none" href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></div>
          </div>
        </li>
      {% empty %}
        You don't have any blogs yet.
      {% endfor %}
    </ul>

    <div class="clearfix">
      <a class="btn btn-primary btn-md mt-4 float-end" role="button" href="{% url 'blogs:new_blog' %}">Create a new blog</a>
    </div>

  {% endif %}

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <h2>Create a new blog</h2>

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="Create blog" %}
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

  <h2>Create a new post</h2>

  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="Create post" %}
  </form>

  <p class="text-end"><a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></p>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>{{ post.title }}</h2>
  <p class="ps-2 fs-5 fw-light">{{ post.date_added|date:'M d, Y H:i' }} by <span class="fs-6 fw-normal">{{ blog.owner }}</span></p>

  <hr />
  <p>{{ post.body|linebreaks }}</p>

  <p class="text-end"><a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></p>

{% endblock content %}